/* Copyright (C) 2015-2025 by Bundesamt fuer Strahlenschutz
 *
 * This file is Free Software under the GNU GPL (v>=3)
 * and comes with ABSOLUTELY NO WARRANTY!
 * See LICENSE for details.
 */

package de.bfs.dokpool.client.content;

import java.time.Year;
import java.util.Map;
import java.util.Set;

import de.bfs.dokpool.client.base.JSON;
import de.bfs.dokpool.client.content.Document.Attribute;
import de.bfs.dokpool.client.content.Document.ChoiceAttribute;

/**
 * Utility classe to hold attribute specifications for dokpool behaviors.
 *
 */
class AttributeSpec {

    private AttributeSpec() {}

    private static String[] yearsSince1987;
    static {
        yearsSince1987 = new String[Year.now().getValue()-1986];
        for (int year = 1987; year <= Year.now().getValue(); year++) {
            yearsSince1987[year-1987] = String.valueOf(year);
        }
    }

    protected static final Attribute[] doksysDates = new Attribute[] {
        new Attribute("SamplingBegin", false, null),
        new Attribute("SamplingEnd", false, null),
        new Attribute("TrajectoryStartTime", false, null),
        new Attribute("TrajectoryEndTime", false, null)
    };

    protected static final ChoiceAttribute[] doksysChoices = new ChoiceAttribute[] {
        new ChoiceAttribute("OperationMode", false, true, "Routine", Set.of(
            "Routine",
            "Intensiv"
        )),

        new ChoiceAttribute("Dom", true, false, null, Set.of(
            "74 _deposition_ground_gamma surface activity_2 h",
            "75 _deposition_ground_gamma surface activity_1 d",
            "76 _deposition_ground_gamma surface activity_1 week",
            "77 _deposition_ground_gamma surface activity_1 month",
            "81 _deposition_ground_beta surface activity, long lived_1 d",
            "82 _deposition_ground_beta surface activity, after 24h_1 d",
            "84 _deposition_ground_beta surface activity_2 h",
            "85 _deposition_ground_beta surface activity_1 d",
            "86 _deposition_ground_beta surface activity_1 week",
            "87 _deposition_ground_beta surface activity_1 month",
            "94 _deposition_ground_alpha surface activity_2 h",
            "95 _deposition_ground_alpha surface activity_1 d",
            "96 _deposition_ground_alpha surface activity_1 week",
            "97 _deposition_ground_alpha surface activity_1 month",
            "100 ___gross dose rate_1 min",
            "101 ___gross dose rate_10 min",
            "102 ___gross dose rate_30 min",
            "103 ___gross dose rate_1 h",
            "104 ___gross dose rate_2 h",
            "105 ___gross dose rate_1 d",
            "107 ___gross dose rate_1 month",
            "109 ___gross dose rate_1 year",
            "110 ___high gross dose rate_",
            "111 ___high gross dose rate_10 min",
            "120 ___net dose rate_",
            "121 ___net dose rate_10 min",
            "123 ___net dose rate_1 h",
            "124 ___net dose rate_2 h",
            "125 ___net dose rate_1 d",
            "130 ___cosmic dose rate_",
            "131 ___cosmic dose rate_10 min",
            "134 ___cosmic dose rate_2 h",
            "135 ___cosmic dose rate_1 d",
            "140 ___terrestrial dose rate_",
            "141 ___terrestrial dose rate_10 min",
            "144 ___terrestrial dose rate_2 h",
            "145 ___terrestrial dose rate_1 d",
            "150 __ground_nuclide-spec. dose rate_",
            "152 __ground_nuclide-spec. dose rate_30 min",
            "153 __ground_nuclide-spec. dose rate_1 h",
            "154 __ground_nuclide-spec. dose rate_2 h",
            "155 ___dose rate_",
            "156 ___dose rate low energy _",
            "157 ___dose rate intermediate energy _",
            "160 _in situ_ground_gamma surface activity wet_",
            "161 _in situ_ground_gamma surface activity wet_10 min",
            "162 _in situ_ground_gamma surface activity wet_30 min",
            "163 _in situ_ground_gamma surface activity wet_1 h",
            "164 _in situ_ground_gamma surface activity wet_2 h",
            "167 _in situ_ground_gamma surface activity wet_1 month",
            "170 _in situ_ground_gamma surface activity_",
            "171 _in situ_ground_gamma surface activity_10 min",
            "172 _in situ_ground_gamma surface activity_30 min",
            "173 _in situ_ground_gamma surface activity_1 h",
            "174 _in situ_ground_gamma surface activity_2 h",
            "177 _in situ_ground_gamma surface activity_1 month",
            "180 _in situ_ground_gamma surface act. Net_",
            "181 _in situ_ground_gamma surface act. Net_10 min",
            "182 _in situ_ground_gamma surface act. Net_30 min",
            "183 _in situ_ground_gamma surface act. Net_1 h",
            "184 _in situ_ground_gamma surface act. Net_2 h",
            "187 _in situ_ground_gamma surface act. Net_1 month",
            "191 __ground_gamma surface activity_",
            "192 _calculated_ground_gamma surface activity_",
            "195 __ground_gamma surface activity concent._",
            "199 __ground__",
            "200 _air_aerosol particles_gamma activity concent._",
            "201 _air_aerosol particles_gamma activity concent._10 min",
            "202 _air_aerosol particles_gamma activity concent._30 min",
            "203 _air_aerosol particles_gamma activity concent._1 h",
            "204 _air_aerosol particles_gamma activity concent._2 h",
            "205 _air_aerosol particles_gamma activity concent._1 d",
            "206 _air_aerosol particles_gamma activity concent._1 week",
            "207 _air_aerosol particles_gamma activity concent._1 month",
            "210 _air_aerosol particles_gamma activity concent._2 weeks",
            "211 _air_aerosol particles_total gamma act. concent._10 min",
            "212 _air_aerosol particles_total gamma act. concent._30 min",
            "213 _air_aerosol particles_total gamma act. concent._1 h",
            "214 _air_aerosol particles_total gamma act. Concent._2 h",
            "220 _air_aerosol particles_artificial beta activity concent._",
            "221 _air_aerosol particles_artificial beta activity concent._10 min",
            "222 _air_aerosol particles_artificial beta activity concent._30 min",
            "223 _air_aerosol particles_artificial beta activity concent._1 h",
            "224 _air_aerosol particles_artificial beta activity concent._2 h",
            "225 _air_aerosol particles_artificial beta activity concent._1 d",
            "230 _air_aerosol particles_beta activity concent._",
            "231 _air_aerosol particles_beta activity concent._10 min",
            "232 _air_aerosol particles_beta activity concent._30 min",
            "233 _air_aerosol particles_beta activity concent._1 h",
            "234 _air_aerosol particles_beta activity concent._2 h",
            "235 _air_aerosol particles_beta activity concent._1 d",
            "237 _air_aerosol particles_beta activity concent._1 month",
            "241 _air_aerosol particles_total beta act.concent._10 min",
            "242 _air_aerosol particles_total beta act.concent._30 min",
            "243 _air_aerosol particles_total beta act.concent._1 h",
            "244 _air_aerosol particles_total beta act.concent._2 h",
            "245 _air_aerosol particles_total beta act.concent._1 d",
            "252 _air_aerosol particles_artificial alpha activity concent._30 min",
            "253 _air_aerosol particles_artificial alpha activity concent._1 h",
            "254 _air_aerosol particles_artificial alpha activity concent._2 h",
            "255 _air_aerosol particles_artificial alpha activity concent._1 d",
            "262 _air_aerosol particles_alpha activity concent._30 min",
            "264 _air_aerosol particles_alpha activity concent._2 h",
            "265 _air_aerosol particles_alpha activity concent._1 d",
            "267 _air_aerosol particles_alpha activity concent._1 month",
            "272 _air_aerosol particles_total alpha act.concent._30 min",
            "274 _air_aerosol particles_total alpha act.concent._2 h",
            "275 _air_aerosol particles_total alpha act.concent._1 d",
            "281 _air_aerosol particles_beta activity concent., long lived_10 min",
            "282 _air_aerosol particles_beta activity concent., long lived_30 min",
            "283 _air_aerosol particles_beta activity concent., long lived_1 h",
            "284 _air_aerosol particles_beta activity concent., long lived_2 h",
            "285 _air_aerosol particles_beta activity concent., long lived_1 d",
            "287 _air_aerosol particles_beta activity concent., long lived_1 month",
            "289 _air_aerosol particles_beta activity concent., 10h later_2h",
            "291 _air_aerosol particles_total emission_10 min",
            "292 _air_aerosol particles_total emission_30 min",
            "300 _air_iodine_activity concentration_",
            "301 _air_iodine_activity concentration_10 min",
            "302 _air_iodine_activity concentration_30 min",
            "304 _air_iodine_activity concentration_2 h",
            "305 _air_iodine_activity concentration_1 d",
            "306 _air_iodine_activity concentration_1 week",
            "307 _air_iodine_activity concentration_2 weeks",
            "309 _air_iodine_activity concentration_4 h",
            "311 _air_iodine_total emission_10 min",
            "312 _air_iodine_total emission_30 min",
            "320 _air_noble gases_activity concentration_",
            "321 _air_noble gases_activity concentration_10 min",
            "322 _air_noble gases_activity concentration_30 min",
            "324 _air_noble gases_activity concentration_2 h",
            "325 _air_noble gases_activity concentration_1 d",
            "327 _air_noble gases_activity concentration_1 month",
            "331 _air_noble gases_high activity concent._10 min",
            "332 _air_noble gases_high activity concent._30 min",
            "341 _air_noble gases_total emission_10 min",
            "342 _air_noble gases_total emission_30 min",
            "353 _air_aerosol particles_gamma activity_1 h",
            "355 _air_aerosol particles_gamma activity_1 d",
            "356 _air_aerosol particles_gamma activity_1 week",
            "357 _air_aerosol particles_gamma activity_1 month",
            "358 _air_aerosol particles_gamma activity_3 months",
            "359 _air_aerosol particles_gamma activity_1 year",
            "363 _air_aerosol particles_beta activity_1 h",
            "365 _air_aerosol particles_beta activity_1 d",
            "366 _air_aerosol particles_beta activity_1 week",
            "367 _air_aerosol particles_beta activity_1 month",
            "368 _air_aerosol particles_beta activity_3 months",
            "369 _air_aerosol particles_beta activity_1 year",
            "373 _air_aerosol particles_total beta activity_1 h",
            "375 _air_aerosol particles_total beta activity_1 d",
            "376 _air_aerosol particles_total beta activity_1 week",
            "377 _air_aerosol particles_total beta activity_1 month",
            "378 _air_aerosol particles_total beta activity_3 months",
            "379 _air_aerosol particles_total beta activity_1 year",
            "383 _air_aerosol particles_alpha activity_1 h",
            "385 _air_aerosol particles_alpha activity_1 d",
            "386 _air_aerosol particles_alpha activity_1 week",
            "387 _air_aerosol particles_alpha activity_1 month",
            "388 _air_aerosol particles_alpha activity_3 months",
            "389 _air_aerosol particles_alpha activity_1 year",
            "393 _air_aerosol particles_total alpha activity_1 h",
            "395 _air_aerosol particles_total alpha activity_1 d",
            "396 _air_aerosol particles_total alpha activity_1 week",
            "397 _air_aerosol particles_total alpha activity_1 month",
            "398 _air_aerosol particles_total alpha activity_3 months",
            "399 _air_aerosol particles_total alpha activity_1 year",
            "403 _air_iodine_activity_1 h",
            "405 _air_iodine_activity_1 d",
            "406 _air_iodine_activity_1 week",
            "407 _air_iodine_activity_1 month",
            "408 _air_iodine_activity_3 months",
            "409 _air_iodine_activity_1 year",
            "411 _air_aerosol particles_alpha activity conc., long lived_10 min",
            "412 _air_aerosol particles_alpha activity conc., long lived_30 min",
            "413 _air_aerosol particles_alpha activity conc., long lived_1 h",
            "414 _air_aerosol particles_alpha activity conc., long lived_2 h",
            "415 _air_aerosol particles_alpha activity conc., long lived_1 d",
            "417 _air_aerosol particles_alpha activity conc., long lived_1 month",
            "423 _air_noble gases_gamma activity_1 h",
            "425 _air_noble gases_gamma activity_1 d",
            "426 _air_noble gases_gamma activity_1 week",
            "427 _air_noble gases_gamma activity_1 month",
            "428 _air_noble gases_gamma activity_3 months",
            "429 _air_noble gases_gamma activity_1 year",
            "433 _air_noble gases_total gamma activity_1 h",
            "435 _air_noble gases_total gamma activity_1 d",
            "436 _air_noble gases_total gamma activity_1 week",
            "437 _air_noble gases_total gamma activity_1 month",
            "438 _air_noble gases_total gamma activity_3 months",
            "439 _air_noble gases_total gamma activity_1 year",
            "443 _air_noble gases_beta activity_1 h",
            "445 _air_noble gases_beta activity_1 d",
            "446 _air_noble gases_beta activity_1 week",
            "447 _air_noble gases_beta activity_1 month",
            "448 _air_noble gases_beta activity_3 months",
            "449 _air_noble gases_beta activity_1 year",
            "453 _air_noble gases_total beta activity_1 h",
            "455 _air_noble gases_total beta activity_1 d",
            "456 _air_noble gases_total beta activity_1 week",
            "457 _air_noble gases_total beta activity_1 month",
            "458 _air_noble gases_total beta activity_3 months",
            "459 _air_noble gases_total beta activity_1 year",
            "563 _air_gases_beta activity_1 h",
            "565 _air_gases_beta activity_1 d",
            "566 _air_gases_beta activity_1 week",
            "567 _air_gases_beta activity_1 month",
            "568 _air_gases_beta activity_3 months",
            "569 _air_gases_beta activity_1 year",
            "573 _air_aerosol particles_beta activity,  long lived_1 h",
            "575 _air_aerosol particles_beta activity,  long lived_1 d",
            "576 _air_aerosol particles_beta activity,  long lived_1 week",
            "577 _air_aerosol particles_beta activity,  long lived_1 month",
            "578 _air_aerosol particles_beta activity,  long lived_3 months",
            "579 _air_aerosol particles_beta activity,  long lived_1 year",
            "583 _air__volume_1 h",
            "585 _air__volume_1 d",
            "586 _air__volume_1 week",
            "587 _air__volume_1 month",
            "588 _air__volume_3 months",
            "589 _air__volume_1 year",
            " ____",
            "591 _air__volume stream_10 min",
            "592 _air__volume stream_30 min",
            "593 _air_stack_temperature_10 min",
            "594 _air_stack_temperature_30 min",
            "595 _air_stack_temperature_1 h",
            "596 _air__temperature_10 min",
            "597 _air__temperature_30 min",
            "598 _air__temperature_1 h",
            "599 _air__overall loss factor _",
            "606 _water__gamma activity_1 week",
            "607 _water__gamma activity_1 month",
            "608 _water__gamma activity_3 months",
            "609 _water__gamma activity_1 year",
            "623 _water__beta activity_1 h",
            "625 _water__beta activity_1 d",
            "626 _water__beta activity_1 week",
            "627 _water__beta activity_1 month",
            "628 _water__beta activity_3 months",
            "629 _water__beta activity_1 year",
            "646 _water__alpha activity_1 week",
            "647 _water__alpha activity_1 month",
            "648 _water__alpha activity_3 months",
            "649 _water__alpha activity_1 year",
            "656 _water__total alpha activity_1 week",
            "657 _water__total alpha activity_1 month",
            "658 _water__total alpha activity_3 months",
            "659 _water__total alpha activity_1 year",
            "661 _water__gamma act.conc._10 min",
            "662 _water__gamma act.conc._30 min",
            "663 _water__gamma act.conc._1 h",
            "664 _water__gamma act.conc._2 h",
            "665 _water__gamma act.conc._1 d",
            "671 _water__specific act.conc._10 min",
            "672 _water__specific act.conc._30 min",
            "673 _water__specific act.conc._1 h",
            "674 _water__specific act.conc._2 h",
            "691 _air__counting rate_10 min",
            "693 _air__counting rate_1 h",
            "695 _air__counting rate_1 d",
            "696 _air__counting rate_1 week",
            "697 _air__counting rate_1 month",
            "698 _air__counting rate_3 months",
            "706 _water__volume_1 week",
            "707 _water__volume_1 month",
            "708 _water__volume_3 months",
            "709 _water__volume_1 year",
            "711 _water__volume stream_10 min",
            "712 _water__volume stream_30 min",
            "716 _water__temperature_10 min",
            "717 _water__temperature_30 min",
            "786 _air_meteo_temperature_10 min",
            "787 _air_meteo_temperature_30 min",
            "788 _air_meteo_temperature_1 h",
            "791 __meteo_air pressure_10 min",
            "793 __meteo_air pressure_1 h",
            "796 __meteo_rel. humidity_10 min",
            "797 __meteo_rel. humidity_1 h",
            "800 __meteo_precipitation_",
            "801 __meteo_precipitation_10 min",
            "802 __meteo_precipitation_30 min",
            "803 __meteo_precipitation_1 h",
            "804 __meteo_precipitation_2 h",
            "805 __meteo_precipitation_1 d",
            "806 __meteo_precipitation_1 wo",
            "807 __meteo_precipitation_1 m",
            "815 __meteo_precipitation snow_1 d",
            "818 __meteo_precipitation probability_15 min",
            "819 __meteo_precipitation probability_2 h",
            "824 __meteo_precipitation intensity_",
            "825 __meteo_precipitation intensity_",
            "827 __meteo_precipitation relativly_10 min",
            "831 __meteo_wind velocity_10 min",
            "832 __meteo_wind velocity_30 min",
            "833 __meteo_wind velocity_1 h",
            "834 __meteo_wind velocity_2 h",
            "836 __meteo_wind veloc. fluctuation (sigma w)_10 min",
            "837 __meteo_wind veloc. fluctuation (sigma w)_30 min",
            "838 __meteo_wind veloc. fluctuation (sigma w)_1 h",
            "841 __meteo_wind direction_10 min",
            "842 __meteo_wind direction_30 min",
            "843 __meteo_wind direction_1 h",
            "844 __meteo_wind direction_2 h",
            "851 __meteo_wind dir. fluctuation (sigma ?)_10 min",
            "852 __meteo_wind dir. fluctuation (sigma ?)_30 min",
            "853 __meteo_wind dir. fluctuation (sigma ?)_1 h",
            "856 __meteo_wind dir. fluctuation (sigma ?)_10 min",
            "857 __meteo_wind dir. fluctuation (sigma ?)_30 min",
            "858 __meteo_wind dir. fluctuation (sigma ?)_1 h",
            "861 __meteo_radiation balance_10 min",
            "862 __meteo_radiation balance_30 min",
            "863 __meteo_radiation balance_1 h",
            "876 __meteo_stability class (1-6) (sigma w)_10 min",
            "877 __meteo_stability class (1-6) (sigma w)_30 min",
            "878 __meteo_stability class (1-6) (sigma w)_1 h",
            "881 __meteo_stability class (1-6) (radiation balance)_10 min",
            "882 __meteo_stability class (1-6) (radiation balance)_30 min",
            "883 __meteo_stability class (1-6) (radiation balance)_1 h",
            "886 __meteo_stability class (1-6) (sigma ?)_10 min",
            "887 __meteo_stability class (1-6) (sigma ?)_30 min",
            "888 __meteo_stability class (1-6) (sigma ?)_1 h",
            "891 __meteo_stability class (1-6) (sigma ?)_10 min",
            "892 __meteo_stability class (1-6) (sigma ?)_30 min",
            "893 __meteo_stability class (1-6) (sigma ?)_1 h",
            "896 __meteo_stability class (1-6) (temp. gradient)_10 min",
            "897 __meteo_stability class (1-6) (temp. gradient)_30 min",
            "898 __meteo_stability class (1-6) (temp. gradient)_1 h",
            "951 ___electrical power_10 min",
            "953 ___electrical power_1 h",
            "955 ___electrical power_1 d",
            "956 ___electrical power_1 week",
            "957 ___electrical power_1 month",
            "958 ___electrical power_3 months",
            "959 ___electrical power_1 year",
            "961 ___therm. power_10 min",
            "963 ___therm. power_1 h",
            "965 ___therm. power_1 d",
            "966 ___therm. power_1 week",
            "967 ___therm. power_1 month",
            "968 ___therm. power_3 months",
            "969 ___therm. power_1 year"
        )),

        new ChoiceAttribute("Duration", false, false, null, Set.of(
            "1a",
            "1Mo",
            "1d",
            "2h",
            "1h",
            "10Min"
        )),

        new ChoiceAttribute("InfoType", false, false, null, Set.of(
            "vorwaerts",
            "rueckwaerts",
            "brutto",
            "netto",
            "nass",
            "trocken",
            "Messergebnisse",
            "Ueberblick",
            "Soll-Ist-Vergleich"
        )),

        new ChoiceAttribute("LegalBase", true, false, null, Set.of(
            "AVV IMIS",
            "EURDEP",
            "IRMIS",
            "DENSE",
            "KFÜ",
            "Land",
            "SPARSE",
            "REI-E",
            "REI-I"
        )),

        new ChoiceAttribute("MeasurementCategory", false, false, null, Set.of(
            "H-3",
            "Be-7",
            "Be-10",
            "C-11",
            "C-14",
            "N-13",
            "O-15",
            "F-18",
            "Ne-19",
            "Na-22",
            "Na-24",
            "Mg-28",
            "Al-26",
            "Al-28",
            "Si-31",
            "Si-32",
            "P-30",
            "P-32",
            "P-33",
            "S-35",
            "Cl-36",
            "Cl-38",
            "Cl-39",
            "Ar-37",
            "Ar-39",
            "Ar-41",
            "K-38",
            "K-40",
            "K-42",
            "K-43",
            "K-44",
            "K-45",
            "Ca-41",
            "Ca-45",
            "Ca-47",
            "Ca-49",
            "Sc-43",
            "Sc-44m",
            "Sc-44",
            "Sc-46",
            "Sc-47",
            "Sc-48",
            "Sc-49",
            "Ti-44",
            "Ti-45",
            "V-47",
            "V-48",
            "V-49",
            "Cr-48",
            "Cr-49",
            "Cr-51",
            "Mn-51",
            "Mn-52m",
            "Mn-52",
            "Mn-53",
            "Mn-54",
            "Mn-56",
            "Fe-52",
            "Fe-55",
            "Fe-59",
            "Fe-60",
            "Co-55",
            "Co-56",
            "Co-57",
            "Co-58m",
            "Co-58",
            "Co-60m",
            "Co-60",
            "Co-61",
            "Co-62m",
            "Ni-56",
            "Ni-57",
            "Ni-59",
            "Ni-63",
            "Ni-65",
            "Ni-66",
            "Cu-60",
            "Cu-61",
            "Cu-62",
            "Cu-64",
            "Cu-66",
            "Cu-67",
            "Zn-62",
            "Zn-63",
            "Zn-65",
            "Zn-69m",
            "Zn-69",
            "Zn-71m",
            "Zn-72",
            "Ga-65",
            "Ga-66",
            "Ga-67",
            "Ga-68",
            "Ga-70",
            "Ga-72",
            "Ga-73",
            "Ge-66",
            "Ge-67",
            "Ge-68",
            "Ge-69",
            "Ge-71",
            "Ge-75",
            "Ge-77",
            "Ge-78",
            "As-69",
            "As-70",
            "As-71",
            "As-72",
            "As-73",
            "As-74",
            "As-76",
            "As-77",
            "As-78",
            "Se-70",
            "Se-73m",
            "Se-73",
            "Se-75",
            "Se-77m",
            "Se-79",
            "Se-81m",
            "Se-81",
            "Se-83",
            "Br-74m",
            "Br-74",
            "Br-75",
            "Br-76",
            "Br-77",
            "Br-80m",
            "Br-80",
            "Br-82",
            "Br-83",
            "Br-84",
            "Kr-74",
            "Kr-76",
            "Kr-77",
            "Kr-79",
            "Kr-81m",
            "Kr-81",
            "Kr-83m",
            "Kr-85m",
            "Kr-85",
            "Kr-87",
            "Kr-88",
            "Kr-89",
            "Rb-79",
            "Rb-80",
            "Rb-81m",
            "Rb-81",
            "Rb-82m",
            "Rb-82",
            "Rb-83",
            "Rb-84",
            "Rb-86",
            "Rb-87",
            "Rb-88",
            "Rb-89",
            "Sr-80",
            "Sr-81",
            "Sr-82",
            "Sr-83",
            "Sr-85m",
            "Sr-85",
            "Sr-87m",
            "Sr-89",
            "Sr-90",
            "Sr-91",
            "Sr-92",
            "Y-86m",
            "Y-86",
            "Y-87",
            "Y-88",
            "Y-90m",
            "Y-90",
            "Y-91m",
            "Y-91",
            "Y-92",
            "Y-93",
            "Y-94",
            "Y-95",
            "Zr-86",
            "Zr-88",
            "Zr-89",
            "Zr-93",
            "Zr-95",
            "Zr-97",
            "Nb-88",
            "Nb-89 1",
            "Nb-89 2",
            "Nb-90",
            "Nb-93m",
            "Nb-94",
            "Nb-95m",
            "Nb-95",
            "Nb-96",
            "Nb-97m",
            "Nb-97",
            "Nb-98",
            "Mo-90",
            "Mo-93m",
            "Mo-93",
            "Mo-99",
            "Mo-101",
            "Tc-93m",
            "Tc-93",
            "Tc-94m",
            "Tc-94",
            "Tc-95m",
            "Tc-95",
            "Tc-96m",
            "Tc-96",
            "Tc-97m",
            "Tc-97",
            "Tc-98",
            "Tc-99m",
            "Tc-99",
            "Tc-101",
            "Tc-104",
            "Ru-94",
            "Ru-97",
            "Ru-103",
            "Ru-105",
            "Ru-106",
            "Rh-99m",
            "Rh-99",
            "Rh-100",
            "Rh-101m",
            "Rh-101",
            "Rh-102m",
            "Rh-102",
            "Rh-103m",
            "Rh-105",
            "Rh-106m",
            "Rh-106",
            "Rh-107",
            "Pd-100",
            "Pd-101",
            "Pd-103",
            "Pd-107",
            "Pd-109",
            "Ag-102",
            "Ag-103",
            "Ag-104m",
            "Ag-104",
            "Ag-105",
            "Ag-106m",
            "Ag-106",
            "Ag-108m",
            "Ag-108",
            "Ag-109m",
            "Ag-110m",
            "Ag-110",
            "Ag-111",
            "Ag-112",
            "Ag-115",
            "Cd-104",
            "Cd-107",
            "Cd-109",
            "Cd-113m",
            "Cd-113",
            "Cd-115m",
            "Cd-115",
            "Cd-117m",
            "Cd-117",
            "In-109",
            "In-110 2",
            "In-110 1",
            "In-111",
            "In-112",
            "In-113m",
            "In-114m",
            "In-114",
            "In-115m",
            "In-115",
            "In-116m",
            "In-117m",
            "In-117",
            "In-119m",
            "In-119",
            "Sn-110",
            "Sn-111",
            "Sn-113",
            "Sn-117m",
            "Sn-119m",
            "Sn-121m",
            "Sn-121",
            "Sn-123m",
            "Sn-123",
            "Sn-125",
            "Sn-126",
            "Sn-127",
            "Sn-128",
            "Sb-115",
            "Sb-116m",
            "Sb-116",
            "Sb-117",
            "Sb-118m",
            "Sb-119",
            "Sb-120 2",
            "Sb-120 1",
            "Sb-122",
            "Sb-124m1",
            "Sb-124m2",
            "Sb-124",
            "Sb-125",
            "Sb-126m",
            "Sb-126",
            "Sb-127",
            "Sb-128 2",
            "Sb-128 1",
            "Sb-129",
            "Sb-130",
            "Sb-131",
            "Te-116",
            "Te-121m",
            "Te-121",
            "Te-123m",
            "Te-123",
            "Te-125m",
            "Te-127m",
            "Te-127",
            "Te-129m",
            "Te-129",
            "Te-131m",
            "Te-131",
            "Te-132",
            "Te-133m",
            "Te-133",
            "Te-134",
            "I-120m",
            "I-120",
            "I-121",
            "I-122",
            "I-123",
            "I-124",
            "I-125",
            "I-126",
            "I-128",
            "I-129",
            "I-130",
            "I-131",
            "I-132m",
            "I-132",
            "I-133",
            "I-134",
            "I-135",
            "Xe-120",
            "Xe-121",
            "Xe-122",
            "Xe-123",
            "Xe-125",
            "Xe-127",
            "Xe-129m",
            "Xe-131m",
            "Xe-133m",
            "Xe-133",
            "Xe-135m",
            "Xe-135",
            "Xe-137",
            "Xe-138",
            "Cs-125",
            "Cs-126",
            "Cs-127",
            "Cs-128",
            "Cs-129",
            "Cs-130",
            "Cs-131",
            "Cs-132",
            "Cs-134m",
            "Cs-134",
            "Cs-135m",
            "Cs-135",
            "Cs-136",
            "Cs-137",
            "Cs-138",
            "Ba-126",
            "Ba-128",
            "Ba-131m",
            "Ba-131",
            "Ba-133m",
            "Ba-133",
            "Ba-135m",
            "Ba-137m",
            "Ba-139",
            "Ba-140",
            "Ba-141",
            "Ba-142",
            "La-131",
            "La-132",
            "La-134",
            "La-135",
            "La-137",
            "La-138",
            "La-140",
            "La-141",
            "La-142",
            "La-143",
            "Ce-134",
            "Ce-135",
            "Ce-137m",
            "Ce-137",
            "Ce-139",
            "Ce-141",
            "Ce-143",
            "Ce-144",
            "Pr-136",
            "Pr-137",
            "Pr-138m",
            "Pr-138",
            "Pr-139",
            "Pr-142m",
            "Pr-142",
            "Pr-143",
            "Pr-144m",
            "Pr-144",
            "Pr-145",
            "Pr-147",
            "Nd-136",
            "Nd-138",
            "Nd-139m",
            "Nd-139",
            "Nd-141m",
            "Nd-141",
            "Nd-147",
            "Nd-149",
            "Nd-151",
            "Pm-141",
            "Pm-142",
            "Pm-143",
            "Pm-144",
            "Pm-145",
            "Pm-146",
            "Pm-147",
            "Pm-148m",
            "Pm-148",
            "Pm-149",
            "Pm-150",
            "Pm-151",
            "Sm-141m",
            "Sm-141",
            "Sm-142",
            "Sm-145",
            "Sm-146",
            "Sm-147",
            "Sm-151",
            "Sm-153",
            "Sm-155",
            "Sm-156",
            "Eu-145",
            "Eu-146",
            "Eu-147",
            "Eu-148",
            "Eu-149",
            "Eu-150 2",
            "Eu-150 1",
            "Eu-152m",
            "Eu-152",
            "Eu-154",
            "Eu-155",
            "Eu-156",
            "Eu-157",
            "Eu-158",
            "Gd-145",
            "Gd-146",
            "Gd-147",
            "Gd-148",
            "Gd-149",
            "Gd-151",
            "Gd-152",
            "Gd-153",
            "Gd-159",
            "Tb-147",
            "Tb-149",
            "Tb-150",
            "Tb-151",
            "Tb-153",
            "Tb-154",
            "Tb-155",
            "Tb-156m2",
            "Tb-156m1",
            "Tb-156",
            "Tb-157",
            "Tb-158",
            "Tb-160",
            "Tb-161",
            "Dy-155",
            "Dy-157",
            "Dy-159",
            "Dy-165",
            "Dy-166",
            "Ho-155",
            "Ho-157",
            "Ho-159",
            "Ho-161",
            "Ho-162m",
            "Ho-162",
            "Ho-164m",
            "Ho-164",
            "Ho-166m",
            "Ho-166",
            "Ho-167",
            "Er-161",
            "Er-165",
            "Er-169",
            "Er-171",
            "Er-172",
            "Tm-162",
            "Tm-166",
            "Tm-167",
            "Tm-170",
            "Tm-171",
            "Tm-172",
            "Tm-173",
            "Tm-175",
            "Yb-162",
            "Yb-166",
            "Yb-167",
            "Yb-169",
            "Yb-175",
            "Yb-177",
            "Yb-178",
            "Lu-169",
            "Lu-170",
            "Lu-171",
            "Lu-172",
            "Lu-173",
            "Lu-174m",
            "Lu-174",
            "Lu-176m",
            "Lu-176",
            "Lu-177m",
            "Lu-177",
            "Lu-178m",
            "Lu-178",
            "Lu-179",
            "Hf-170",
            "Hf-172",
            "Hf-173",
            "Hf-175",
            "Hf-177m",
            "Hf-178m",
            "Hf-179m",
            "Hf-180m",
            "Hf-181",
            "Hf-182m",
            "Hf-182",
            "Hf-183",
            "Hf-184",
            "Ta-172",
            "Ta-173",
            "Ta-174",
            "Ta-175",
            "Ta-176",
            "Ta-177",
            "Ta-178 2",
            "Ta-178 1",
            "Ta-179",
            "Ta-180m",
            "Ta-180",
            "Ta-182m",
            "Ta-182",
            "Ta-183",
            "Ta-184",
            "Ta-185",
            "Ta-186",
            "W-176",
            "W-177",
            "W-178",
            "W-179",
            "W-181",
            "W-185",
            "W-187",
            "W-188",
            "Re-177",
            "Re-178",
            "Re-180",
            "Re-181",
            "Re-182 2",
            "Re-182 1",
            "Re-184m",
            "Re-184",
            "Re-186m",
            "Re-186",
            "Re-187",
            "Re-188m",
            "Re-188",
            "Re-189",
            "Os-180",
            "Os-181",
            "Os-182",
            "Os-185",
            "Os-189m",
            "Os-190m",
            "Os-191m",
            "Os-191",
            "Os-193",
            "Os-194",
            "Ir-182",
            "Ir-184",
            "Ir-185",
            "Ir-186 1",
            "Ir-186 2",
            "Ir-187",
            "Ir-188",
            "Ir-189",
            "Ir-190m2",
            "Ir-190m1",
            "Ir-190",
            "Ir-191m",
            "Ir-192m",
            "Ir-192",
            "Ir-194m",
            "Ir-194",
            "Ir-195m",
            "Ir-195",
            "Pt-186",
            "Pt-188",
            "Pt-189",
            "Pt-191",
            "Pt-193m",
            "Pt-193",
            "Pt-195m",
            "Pt-197m",
            "Pt-197",
            "Pt-199",
            "Pt-200",
            "Au-193",
            "Au-194",
            "Au-195m",
            "Au-195",
            "Au-198m",
            "Au-198",
            "Au-199",
            "Au-200m",
            "Au-200",
            "Au-201",
            "Hg-193m",
            "Hg-193",
            "Hg-194",
            "Hg-195m",
            "Hg-195",
            "Hg-197m",
            "Hg-197",
            "Hg-199m",
            "Hg-203",
            "Tl-194m",
            "Tl-194",
            "Tl-195",
            "Tl-197",
            "Tl-198m",
            "Tl-198",
            "Tl-199",
            "Tl-200",
            "Tl-201",
            "Tl-202",
            "Tl-204",
            "Tl-206",
            "Tl-207",
            "Tl-208",
            "Tl-209",
            "Pb-195m",
            "Pb-198",
            "Pb-199",
            "Pb-200",
            "Pb-201",
            "Pb-202m",
            "Pb-202",
            "Pb-203",
            "Pb-205",
            "Pb-209",
            "Pb-210",
            "Pb-211",
            "Pb-212",
            "Pb-214",
            "Bi-200",
            "Bi-201",
            "Bi-202",
            "Bi-203",
            "Bi-205",
            "Bi-206",
            "Bi-207",
            "Bi-210m",
            "Bi-210",
            "Bi-211",
            "Bi-212",
            "Bi-213",
            "Bi-214",
            "Po-203",
            "Po-205",
            "Po-207",
            "Po-210",
            "Po-211",
            "Po-212",
            "Po-213",
            "Po-214",
            "Po-215",
            "Po-216",
            "Po-218",
            "At-207",
            "At-211",
            "At-215",
            "At-216",
            "At-217",
            "At-218",
            "Rn-218",
            "Rn-219",
            "Rn-220",
            "Rn-222",
            "Fr-219",
            "Fr-220",
            "Fr-221",
            "Fr-222",
            "Fr-223",
            "Ra-222",
            "Ra-223",
            "Ra-224",
            "Ra-225",
            "Ra-226",
            "Ra-227",
            "Ra-228",
            "Ac-223",
            "Ac-224",
            "Ac-225",
            "Ac-226",
            "Ac-227",
            "Ac-228",
            "Th-226",
            "Th-227",
            "Th-228",
            "Th-229",
            "Th-230",
            "Th-231",
            "Th-232",
            "Th-234",
            "Pa-227",
            "Pa-228",
            "Pa-230",
            "Pa-231",
            "Pa-232",
            "Pa-233",
            "Pa-234m",
            "Pa-234",
            "U-230",
            "U-231",
            "U-232",
            "U-233",
            "U-234",
            "U-235",
            "U-236",
            "U-237",
            "U-238",
            "U-239",
            "U-240",
            "Np-232",
            "Np-233",
            "Np-234",
            "Np-235",
            "Np-236 2",
            "Np-236 1",
            "Np-237",
            "Np-238",
            "Np-239",
            "Np-240m",
            "Np-240",
            "Pu-234",
            "Pu-235",
            "Pu-236",
            "Pu-237",
            "Pu-238",
            "Pu-239",
            "Pu-240",
            "Pu-241",
            "Pu-242",
            "Pu-243",
            "Pu-244",
            "Pu-245",
            "Pu-246",
            "Am-237",
            "Am-238",
            "Am-239",
            "Am-240",
            "Am-241",
            "Am-242m",
            "Am-242",
            "Am-243",
            "Am-244m",
            "Am-244",
            "Am-245",
            "Am-246m",
            "Am-246",
            "Cm-238",
            "Cm-240",
            "Cm-241",
            "Cm-242",
            "Cm-243",
            "Cm-244",
            "Cm-245",
            "Cm-246",
            "Cm-247",
            "Cm-248",
            "Cm-249",
            "Cm-250",
            "Bk-245",
            "Bk-246",
            "Bk-247",
            "Bk-249",
            "Bk-250",
            "Cf-244",
            "Cf-246",
            "Cf-248",
            "Cf-249",
            "Cf-250",
            "Cf-251",
            "Cf-252",
            "Cf-253",
            "Cf-254",
            "Es-250",
            "Es-251",
            "Es-253",
            "Es-254m",
            "Es-254",
            "Fm-252",
            "Fm-253",
            "Fm-254",
            "Fm-255",
            "Fm-257",
            "Md-257",
            "Md-258",
            "Pu-23940",
            "I-131G",
            "I-133G",
            "I-135G",
            "I-131E",
            "I-133E",
            "I-135E",
            "I-131O",
            "I-133O",
            "I-135O",
            "I-131GO",
            "I-133GO",
            "I-135GO",
            "Gamma-ODL",
            "G-Gamma",
            "G-Beta",
            "G-Beta-kuenstl.",
            "G-Alpha",
            "G-Alpha-kuenstl.",
            "Cs-Gesamt",
            "Rest-Beta",
            "G-Gamma-kuenstl.",
            "Gamma-ODL-Brutto",
            "Gamma-ODL-Netto",
            "Gamma-ODL-kuenstl.",
            "Gamma-OD",
            "Neutronen-OD",
            "Neutronen-ODL",
            "G-Alpha-2,5h_verz",
            "G-Alpha-5h_verz",
            "G-Alpha-24h_verz",
            "G-Alpha-120h_verz",
            "G-Beta-2h_verz",
            "G-Beta-10h_verz",
            "G-Beta-24h_verz",
            "G-Beta-120h_verz",
            "G-Alpha-natuerl.",
            "G-Beta-natuerl.",
            "Gamma-OD-Brutto",
            "Gamma-OD-Netto",
            "Neutr-OD-Brutto",
            "Neutr-OD-Netto",
            "Neutr-ODL-Brutto",
            "Neutr-ODL-Netto",
            "Regen",
            "Schnee",
            "Niederschlag",
            "Summe",
            "SumPARK",
            "Sumrelv",
            "U-nat",
            "Cm-24344",
            "Gamma-ODL-min",
            "Gamma-ODL-max",
            "Neutr-ODL-min",
            "Neutr-ODL-max",
            "Rn-Gesamt",
            "Nullmessung",
            "Temperatur"
        )),

        new ChoiceAttribute("MeasuringProgram", false, false, null, Set.of(
            "Intensivmessprogramm",
            "Routinemessprogramm",
            "REI",
            "Spontanproben Bund"
        )),

        new ChoiceAttribute("NetworkOperator", true, false, null, Set.of(
            "Schleswig-Holstein",
            "Hamburg",
            "Niedersachsen",
            "Bremen",
            "Nordrhein-Westfalen",
            "Hessen",
            "Rheinland-Pfalz",
            "Baden-Wuerttemberg",
            "Bayern",
            "Saarland",
            "Berlin",
            "Brandenburg",
            "Mecklenburg-Vorpommern",
            "Sachsen",
            "Sachsen-Anhalt",
            "Thueringen",
            "Bundeswehr",
            "Endlager (Bundesaufsicht)",
            "ZdB-Testnetz",
            "BfS (Spuren)",
            "vTI",
            "BfS/ZdB",
            "BfE",
            "FhG",
            "BfG",
            "BSH",
            "BfS (LSt. AB)",
            "BfS (LSt. TW ...)",
            "BMU",
            "MRI",
            "Park",
            "Sonstige",
            "PTB",
            "BfS (ABI)",
            "DWD",
            "auslaend. Messnetze",
            "BfS (ODL)"
        ), Map.ofEntries(
            Map.entry("A","BfS (Spuren)"),
            Map.entry("B","vTI"),
            Map.entry("D","BfS/ZdB"),
            Map.entry("E","BfE"),
            Map.entry("I","BfS (LSt. AB)"),
            Map.entry("L","BfS (LSt. TW ...)"),
            Map.entry("M","BMUB"),
            Map.entry("N","MRI"),
            Map.entry("S","Sonstige"),
            Map.entry("T","PTB"),
            Map.entry("U","BfS (ABI)"),
            Map.entry("W","DWD"),
            Map.entry("Z","BfS (ODL)"),
            Map.entry("01","Schleswig-Holstein"),
            Map.entry("02","Hamburg"),
            Map.entry("03","Niedersachsen"),
            Map.entry("04","Bremen"),
            Map.entry("05","Nordrhein-Westfalen"),
            Map.entry("06","Hessen"),
            Map.entry("07","Rheinland-Pfalz"),
            Map.entry("08","Baden-Wuerttemberg"),
            Map.entry("09","Bayern"),
            Map.entry("10","Saarland"),
            Map.entry("11","Berlin"),
            Map.entry("12","Brandenburg"),
            Map.entry("13","Mecklenburg-Vorpommern"),
            Map.entry("14","Sachsen"),
            Map.entry("15","Sachsen-Anhalt"),
            Map.entry("16","Thueringen"),
            Map.entry("18","Endlager (Bundesaufsicht)"),
            Map.entry("19","ZdB-Testnetz"),
            Map.entry("17","Bundeswehr"),
            Map.entry("G","BfG"),
            Map.entry("H","BSH"),
            Map.entry("X","auslaend. Messnetze")
        )),

        new ChoiceAttribute("Purpose", false, false, null, Set.of(
            "Standard-Info Bundesmessnetze",
            "Standard-Info DWD"
        )),

        new ChoiceAttribute("SampleType", true, false, null, Set.of(
            "A",
            "A1",
            "A11",
            "A12",
            "A13",
            "A2",
            "A21",
            "A22",
            "A23",
            "A24",
            "A3",
            "A31",
            "A32",
            "A4",
            "A41",
            "A42",
            "A5",
            "A51",
            "A52",
            "A53",
            "A54",
            "A55",
            "A56",
            "B",
            "B1",
            "B11",
            "B12",
            "B13",
            "B2",
            "B21",
            "B22",
            "B3",
            "B31",
            "B32",
            "B33",
            "B34",
            "B35",
            "B36",
            "F",
            "F1",
            "F11",
            "F12",
            "F2",
            "F21",
            "F3",
            "F31",
            "F4",
            "F41",
            "F5",
            "F51",
            "F52",
            "F5Z",
            "F6",
            "F61",
            "F62",
            "F63",
            "F7",
            "F71",
            "G",
            "G1",
            "G11",
            "G12",
            "G13",
            "G2",
            "G21",
            "G22",
            "G23",
            "G3",
            "G31",
            "G32",
            "G33",
            "G4",
            "G41",
            "G5",
            "G51",
            "G52",
            "G53",
            "GZ",
            "GZ1",
            "I",
            "I1",
            "I11",
            "I12",
            "I13",
            "I14",
            "I15",
            "I19",
            "I2",
            "I21",
            "I22",
            "I3",
            "I31",
            "I32",
            "L",
            "L1",
            "L11",
            "L12",
            "L2",
            "L21",
            "L22",
            "L3",
            "L31",
            "L32",
            "L4",
            "L41",
            "L42",
            "L43",
            "L44",
            "L45",
            "L46",
            "L5",
            "L51",
            "L52",
            "L53",
            "L54",
            "L6",
            "L61",
            "L62",
            "L63",
            "M",
            "N",
            "N1",
            "N11",
            "N12",
            "N13",
            "N14",
            "N15",
            "N2",
            "N21",
            "N22",
            "N23",
            "N24",
            "N25",
            "N26",
            "N27",
            "N28",
            "N29",
            "N2A",
            "N2B",
            "N2C",
            "N2Y",
            "N2Z",
            "N3",
            "N31",
            "N3Z",
            "N4",
            "N41",
            "N42",
            "N43",
            "N44",
            "N45",
            "N46",
            "N4Z",
            "N5",
            "N51",
            "N52",
            "N53",
            "N54",
            "N55",
            "N56",
            "N5Z",
            "N6",
            "N61",
            "N62",
            "N63",
            "N64",
            "N65",
            "N7",
            "N71",
            "N72",
            "N73",
            "N74",
            "N75",
            "N76",
            "N8",
            "N81",
            "N82",
            "N83",
            "N84",
            "N85",
            "N86",
            "N87",
            "N9",
            "N91",
            "N92",
            "N93",
            "N94",
            "N95",
            "N96",
            "N97",
            "N98",
            "N99",
            "N9A",
            "N9B",
            "N9C",
            "N9D",
            "N9E",
            "N9F",
            "N9G",
            "N9H",
            "N9I",
            "N9J",
            "N9K",
            "N9L",
            "N9M",
            "N9N",
            "N9O",
            "N9P",
            "N9Q",
            "N9R",
            "NZ",
            "NZ1",
            "NZ2",
            "NZ3",
            "S",
            "S1",
            "S11",
            "S12",
            "S13",
            "S14",
            "S2",
            "S21",
            "S22",
            "S23",
            "S3",
            "S31",
            "S32",
            "S4",
            "S41",
            "S42",
            "S43",
            "SF1",
            "SF2",
            "SF3",
            "SF4",
            "SF5",
            "SG1",
            "SG2",
            "SG3",
            "SG4",
            "SG5",
            "SG6",
            "SO1",
            "SO2",
            "SO3",
            "SO4",
            "SO5",
            "Z",
            "Z1",
            "Z11",
            "Z12",
            "Z13",
            "Z14",
            "Z2",
            "Z21",
            "Z22",
            "Z3",
            "Z31",
            "Z32",
            "Z33",
            "Z34",
            "Z35"
        )),

        new ChoiceAttribute("Status", false, false, null, Set.of(
            "geprueft",
            "nicht geprueft"
        )),
    };

    protected static final ChoiceAttribute[] rodosChoices = new ChoiceAttribute[] {
        new ChoiceAttribute("PrognosisType", false, true, "Sonstige Ausbreitungsrechnung", Set.of(
            "Sonstige Ausbreitungsrechnung",
            "Potenziell betroffene Gebiete",
            "RODOS Prognose",
            "DWD Ausbreitungsrechnung ab Quelle",
            "LASAIR/LASAT"
        )),
        new ChoiceAttribute("PrognosisForm", false, false, null, Set.of(
            "Routinerechnung",
            "Einzelrechnung"
        )),
    };

    protected static final ChoiceAttribute[] reiChoices = new ChoiceAttribute[] {

        new ChoiceAttribute("Authority", false, true, "", Set.of(
            "de_bw",
            "de_by",
            "de_be",
            "de_bb",
            "de_hb",
            "de_el",
            "de_hh",
            "de_he",
            "de_mv",
            "de_ni",
            "de_nw",
            "de_rp",
            "de_sl",
            "de_sn",
            "de_st",
            "de_sh",
            "de_th"
        )),

        new ChoiceAttribute("MStIDs", true, true, new JSON.Node("null"), Set.of(
            "00000",
            "00001",
            "01002",
            "01010",
            "01011",
            "01020",
            "01051",
            "01071",
            "01081",
            "01181",
            "01551",
            "03020",
            "03040",
            "03060",
            "03102",
            "03132",
            "03141",
            "03151",
            "03161",
            "03171",
            "03191",
            "03201",
            "03211",
            "03221",
            "03231",
            "03561",
            "03571",
            "04020",
            "04032",
            "05020",
            "05030",
            "05040",
            "05050",
            "05060",
            "05080",
            "05090",
            "05091",
            "05092",
            "05141",
            "05151",
            "05161",
            "05171",
            "05181",
            "06060",
            "06101",
            "06122",
            "06501",
            "07002",
            "07010",
            "07020",
            "07030",
            "07040",
            "07071",
            "07081",
            "08002",
            "08010",
            "08031",
            "08041",
            "08061",
            "08082",
            "08101",
            "08111",
            "08121",
            "08131",
            "08201",
            "08210",
            "08221",
            "08511",
            "08521",
            "09030",
            "09051",
            "09052",
            "09081",
            "09082",
            "09111",
            "09121",
            "09122",
            "09123",
            "09131",
            "09141",
            "09151",
            "09161",
            "09162",
            "09171",
            "09181",
            "09192",
            "09231",
            "09300",
            "09521",
            "09531",
            "09541",
            "10010",
            "10030",
            "10042",
            "11010",
            "11020",
            "11042",
            "11061",
            "12010",
            "12032",
            "12041",
            "13002",
            "13010",
            "13031",
            "13032",
            "13033",
            "14002",
            "14010",
            "14032",
            "14040",
            "14041",
            "15010",
            "18001",
            "18002",
            "18003"
        )),

        new ChoiceAttribute("NuclearInstallations", true, true, null, Set.of(
            "UCHL",
            "UELA",
            "UELM",
            "UFRC",
            "UFRF",
            "U01A",
            "U01B",
            "U01C",
            "U01D",
            "U01I",
            "U01K",
            "U01L",
            "U01M",
            "U03A",
            "U03B",
            "U03C",
            "U03E",
            "U03G",
            "U03K",
            "U03L",
            "U03P",
            "U03S",
            "U03U",
            "U03Z",
            "U05B",
            "U05F",
            "U05G",
            "U05K",
            "U05T",
            "U05U",
            "U06B",
            "U07M",
            "U07U",
            "U08H",
            "U08K",
            "U08M",
            "U08N",
            "U08O",
            "U08P",
            "U08W",
            "U09A",
            "U09B",
            "U09C",
            "U09D",
            "U09E",
            "U09F",
            "U09G",
            "U09H",
            "U09I",
            "U09J",
            "U09K",
            "U11B",
            "U12R",
            "U13A",
            "U13B",
            "U14R",
            "U15M"
        )),

        new ChoiceAttribute("Origins", false, true, null, Set.of(
            "Strahlenschutzverantwortlicher",
            "unabhaengige Messstelle"
        )),

        new ChoiceAttribute("PDFVersion", false, true, "keine Angabe", Set.of(
            "keine Angabe",
            "PDF/A-1b",
            "PDF/A-1a",
            "PDF/A-2a",
            "PDF/A-2b",
            "PDF/A-2u",
            "PDF/A-3a",
            "PDF/A-3b",
            "PDF/A-3u"
        )),

        new ChoiceAttribute("Period", false, true, null, Set.of("Y",
            "H1",
            "H2",
            "Q1",
            "Q2",
            "Q3",
            "Q4",
            "M1",
            "M2",
            "M3",
            "M4",
            "M5",
            "M6",
            "M7",
            "M8",
            "M9",
            "M10",
            "M11",
            "M12"
        )),

        new ChoiceAttribute("ReiLegalBases", true, true, null, Set.of(
            "REI-E",
            "REI-I"
        )),

        new ChoiceAttribute("Year", false, true, null, Set.of(yearsSince1987)),
    };


}
